repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: trim trailing whitespace
      - id: end-of-file-fixer
        name: fix end of files
      - id: check-added-large-files
        name: check for added large files
      - id: check-merge-conflict
        name: check for merge conflicts
      - id: detect-private-key
        name: detect private key
      - id: mixed-line-ending
        name: mixed line ending
        args: ['--fix=lf']
      - id: check-executables-have-shebangs
        name: check executables have shebangs
      - id: check-shebang-scripts-are-executable
        name: check shebang scripts are executable

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        name: detect secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: '^(\.env|xseed\.sh)$'

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        name: shellcheck
        args: ['--severity=warning']
        exclude: '^\.env'

  - repo: local
    hooks:
      - id: bash-syntax
        name: bash syntax check
        entry: bash -n
        language: system
        types: [shell]
        exclude: '^\.env'
