---
name: ShellCheck

"on":
  push:
    branches: [main]
    paths:
      - "**/*.sh"
  pull_request:
    paths:
      - "**/*.sh"

permissions:
  contents: read

jobs:
  shellcheck:
    name: Run ShellCheck
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6

      - uses: ludeeus/action-shellcheck@2.0.0
        with:
          severity: warning
